dist: trusty
sudo: false
osx_image: xcode8

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - doxygen
      - libboost-dev
      - libboost-test-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 2
  - make -j 2 check

matrix:
  include:
    - if: branch = master
      os: linux
      script:
        - bash doc/publish_documentation.sh
