dist: trusty
sudo: false

language: cpp

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 2
  - make -j 2 check

matrix:
  include:
    - os: linux
      compiler: clang
      env: Boost=1.54.0
      addons:
        apt:
          packages:
            - libboost-dev
            - libboost-test-dev
    - os: linux
      compiler: gcc
      env: Boost=1.54.0
      addons:
        apt:
          packages:
            - libboost-dev
            - libboost-test-dev
    - os: linux
      compiler: clang
      env: Boost=1.55.0
      addons:
        apt:
          packages:
            - libboost1.55-dev
            - libboost-test1.55-dev
    - os: linux
      compiler: gcc
      env: Boost=1.55.0
      addons:
        apt:
          packages:
            - libboost1.55-dev
            - libboost-test1.55-dev
    - os: osx
      compiler: clang
    - if: branch = master
      os: linux
      env: docs=yes
      addons:
        apt:
          packages:
            - doxygen
            - libboost-dev
            - libboost-test-dev
      script:
        - bash doc/publish_documentation.sh

  allow_failures:
    - env: docs=yes
