dist: trusty
sudo: false

language: cpp

addons:
  apt:
    packages:
      - doxygen
      - libboost-dev
      - libboost-test-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j 2
  - make -j 2 check

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang
    - if: branch = master
      os: linux
      script:
        - bash doc/publish_documentation.sh
